package com.mucommander.extensions;

public enum ContextMenuExtensionPositions {
	TOP, BOTTOM,

	OPEN_BLOCK_TOP, OPEN_BLOCK_BOTTOM,

	SELECT_BLOCK_TOP, SELECT_BLOCK_BOTTOM,

	CAN_OPEN_IN_FILE_MANAGER,

	DELETE_BLOCK_TOP, DELETE_BLOCK_BOTTOM,

	PROPERTIES_BLOCK_TOP, PROPERTIES_BLOCK_BOTTOM;
}
