#!/bin/bash

# PagaVCS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# PagaVCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PagaVCS;  If not, see <http://www.gnu.org/licenses/>.

if [ ! -f /tmp/pagavcs/server-running-indicator ]
then
    java -Xmx99m -jar /usr/share/pagavcs/bin/pagavcs.jar &

    # waiting server to boot up    
    while [ ! -f /tmp/pagavcs/server-running-indicator ]; do
       sleep 0.5s
    done
fi

echo $@ > /dev/tcp/localhost/12905
RETVAL=$?
if [ $RETVAL != 0 ]
then
    rm /tmp/pagavcs/server-running-indicator
    java -Xmx99m -jar /usr/share/pagavcs/bin/pagavcs.jar &

    # waiting server to boot up    
    while [ ! -f /tmp/pagavcs/server-running-indicator ]; do
       sleep 0.5s
    done
    echo $@ > /dev/tcp/localhost/12905
fi
