#!/bin/bash

# PagaVCS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# PagaVCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PagaVCS;  If not, see <http://www.gnu.org/licenses/>.

# don't wakeup server for stop command
if [ "$1" == "stop" ];
then
	echo stop server
	echo "stop" > /dev/tcp/localhost/12905
	exit
fi

# don't allow to be run as root
whoami=`whoami`
if [ "${whoami}" == "root" ];
then
	exit
fi

if [ ! -f /tmp/pagavcs/server-running-indicator ];
then
    echo server not running, start a new PagaVCS server
    java -Xmx99m -jar /usr/share/pagavcs/bin/pagavcs.jar &

    # waiting server to boot up    
    while [ ! -f /tmp/pagavcs/server-running-indicator ]; do
       sleep 0.5s
    done
fi

echo "send command to server: $@"
echo "$@" > /dev/tcp/localhost/12905
RETVAL=$?
if [ $RETVAL != 0 ];
then
	echo "failed, (re)starting server"
    rm -f /tmp/pagavcs/server-running-indicator
    java -Xmx99m -jar /usr/share/pagavcs/bin/pagavcs.jar &

    # waiting server to boot up    
    while [ ! -f /tmp/pagavcs/server-running-indicator ]; do
       sleep 0.5s
    done
    echo "resend command to server: $@"
    echo $@ > /dev/tcp/localhost/12905
else
	echo successfull
fi
